/** VT GIS + BT map adapter. Shapes are normalized here, never guessed or generated.
 * See HANDOFF.md for the proposed JSON contract to confirm with the GIS team.
 */
const SVG_NS='http://www.w3.org/2000/svg';
export function coordinate(point){return Array.isArray(point)&&point.length>=2&&Number.isFinite(point[0])&&Number.isFinite(point[1])&&Math.abs(point[0])<=180&&Math.abs(point[1])<=90;}
export function geoFeatures(value){return value?.type==='FeatureCollection'&&Array.isArray(value.features)?value.features.filter(f=>f?.type==='Feature'&&['Point','LineString','MultiLineString','Polygon','MultiPolygon'].includes(f.geometry?.type)&&Array.isArray(f.geometry.coordinates)):[];}
// The teammate's as_dict() models use [lat, lon], unlike GeoJSON.
export function modelGeometry(points,type){
 const coords=Array.isArray(points)?points.filter(p=>Array.isArray(p)&&coordinate([p[1],p[0]])).map(p=>[p[1],p[0]]):[];
 if(coords.length<(type==='Polygon'?3:2))return null;
 if(type==='Polygon'&&String(coords[0])!==String(coords.at(-1)))coords.push([...coords[0]]);
 return {type,coordinates:type==='Polygon'?[coords]:coords};
}
export function buildingFeatures(payload){
 if(payload?.type==='FeatureCollection')return geoFeatures(payload);
 const rows=Array.isArray(payload)?payload:payload?.buildings;
 if(!Array.isArray(rows))return [];
 return rows.flatMap(row=>{const b=row.building||row;const geometry=modelGeometry(b.geometry,'Polygon')||(coordinate([b.lon,b.lat])?{type:'Point',coordinates:[b.lon,b.lat]}:null);
 return geometry&&b.building_id!=null?[{type:'Feature',id:String(b.building_id),geometry,properties:{id:String(b.building_id),name:b.name,provenance:b.provenance,accessible_entrances:Array.isArray(row.entrances)?row.entrances.filter(e=>e.accessible).map(e=>({name:e.entrance_type,coordinates:[e.lon,e.lat]})):undefined}}]:[];});
}
export function normalizedRoute(data){
 if(!data||typeof data!=='object')return {status:'unavailable',reason:'Invalid route response.'};
 if(data.status==='unavailable'||data.status==='no_route')return {...data,geometry:null};
 const geometry=Array.isArray(data.geometry)?modelGeometry(data.geometry,'LineString'):null;
 return {...data,geometry:geometry?{type:'FeatureCollection',features:[{type:'Feature',geometry,properties:{source:data.fallback?'Straight-line estimate':'VT GIS',abandoned:Boolean(data.fallback)}}]}:data.geometry};
}
export function routePayload(origin,destination,mode){if(!origin||!destination)throw new Error('Choose a starting building and destination.');if(origin===destination)throw new Error('Choose two different buildings.');if(!['fastest','least_walking','ada_walking'].includes(mode))throw new Error('Choose a supported route mode.');return {origin:{building_id:origin},destination:{building_id:destination},mode};}
export function busStatus(vehicle,replay){const delta=vehicle.sched_delta_min;const timing=typeof delta==='number'&&Number.isFinite(delta)?`${Math.abs(delta).toFixed(1)} min ${delta<0?'early':delta>0?'late':'from schedule'}`:'Schedule deviation unavailable';return `${replay?'Replayed observation':vehicle.is_stale?'Stale observation':'Observed position'} · ${timing}`;}
function svg(tag,attributes={}){const node=document.createElementNS(SVG_NS,tag);for(const [key,value] of Object.entries(attributes))node.setAttribute(key,String(value));return node;}
function text(parent,tag,value,className){const el=document.createElement(tag);el.textContent=value;if(className)el.className=className;parent.append(el);return el;}
function paths(geometry){if(geometry?.type==='LineString')return [geometry.coordinates];if(geometry?.type==='MultiLineString'||geometry?.type==='Polygon')return geometry.coordinates;if(geometry?.type==='MultiPolygon')return geometry.coordinates.flat();return [];}
function allPoints(features){return features.flatMap(f=>f.geometry.type==='Point'?[f.geometry.coordinates]:paths(f.geometry).flat()).filter(coordinate);}
export function mountGIS(root,{apiBase='',fallbackUrl='',destinationHint='',onDestination}={}){
 let alive=true,buildings=[],mapData={},routeData=null,abort=new AbortController(),poll,view=[0,0,600,380],drag=null,watch=null,device=null;
 const url=path=>`${apiBase}${path}`;
 root.innerHTML=`<label class="helper">Find buildings<input class="gis-search" type="search" placeholder="Search building name, e.g. McBryde"></label><div class="gis-toolbar"><label>From<select class="gis-origin"><option value="">Choose a building</option></select></label><label>To<select class="gis-destination"><option value="">Choose a building</option></select></label></div><div class="gis-modes" role="group" aria-label="Route preference"><button data-mode="fastest" aria-pressed="true">Walking</button><button data-mode="ada_walking" aria-pressed="false">ADA Walking</button></div><p class="helper">Walking routes · choose a standard or accessible path.</p><button class="secondary gis-route" type="button">Find campus route →</button><div class="gis-viewport" tabindex="0" role="group" aria-label="Campus map. Arrow keys pan, plus and minus zoom."><div class="gis-canvas"></div><div class="gis-zoom"><button aria-label="Zoom in">+</button><button aria-label="Zoom out">−</button><button aria-label="Reset map view">↺</button></div><p class="gis-empty">Loading campus map…</p></div><div class="gis-selection" hidden></div><p class="gis-status helper" role="status">Find a building to get started.</p><div class="gis-actions"><button class="text-button gis-retry">Refresh map</button><button class="text-button gis-locate">Use my location</button></div><p class="helper gis-location-note">Your location stays private and is never saved.</p><p class="helper">Virginia Tech Campus Planning, Infrastructure, and Facilities (CPIF) GIS. Not a survey product. Verify closures and accessible routes on site.</p><div class="gis-route-summary"></div>`;
 const find=s=>root.querySelector(s),origin=find('.gis-origin'),destination=find('.gis-destination'),status=find('.gis-status'),canvas=find('.gis-canvas'),empty=find('.gis-empty'),panel=find('.gis-selection');
 let mode='fastest',mapSVG,loadVersion=0;
 async function request(path,options={}){const response=await fetch(url(path),{...options,signal:abort.signal,headers:{'Content-Type':'application/json','X-HokieFlow-Request':'1',...options.headers}});if(!response.ok)throw new Error('Campus map service is unavailable. Try again shortly.');return response.json();}
 function selectBuilding(feature){const props=feature.properties||{};panel.hidden=false;panel.replaceChildren();text(panel,'strong',props.name||'Campus building');for(const [label,target] of [['Set as origin',origin],['Set as destination',destination]]){const button=text(panel,'button',label,'text-button');button.type='button';button.onclick=()=>{target.value=String(props.id??feature.id);if(target===destination)onDestination?.(props);};}const entrances=props.accessible_entrances;text(panel,'p',Array.isArray(entrances)&&entrances.length?`${entrances.length} accessible entrance(s) supplied by VT GIS. Markers shown where coordinates are provided.`:'No entrance details available.','helper');}
 function renderMap(){
  const buildingFeatures=buildings;
  const closureFeatures=Array.isArray(mapData.closures)?mapData.closures.flatMap(c=>{const geometry=modelGeometry(c.geometry,'Polygon');return geometry?[{type:'Feature',geometry,properties:{kind:'closure',name:c.name}}]:[]}):geoFeatures(mapData.closures);
  const layers=[...buildingFeatures,...geoFeatures(mapData.routes),...closureFeatures,...geoFeatures(routeData?.geometry)];
  const entrances=buildings.flatMap(f=>(Array.isArray(f.properties?.accessible_entrances)?f.properties.accessible_entrances:[]).filter(e=>coordinate(e.coordinates)).map(e=>({type:'Feature',geometry:{type:'Point',coordinates:e.coordinates},properties:{kind:'entrance',name:e.name||'Accessible entrance'}})));
  layers.push(...entrances);
  const vehicles=Array.isArray(mapData.vehicles)?mapData.vehicles.filter(v=>coordinate([v.lon,v.lat])):[];
  const points=[...allPoints(layers),...vehicles.map(v=>[v.lon,v.lat]),...(device?[[device.lon,device.lat]]:[])];
  canvas.replaceChildren();if(!points.length){empty.hidden=false;empty.textContent='Your next stop starts here.';if(fallbackUrl){const image=document.createElement('img');image.src=fallbackUrl;image.alt='Offline campus schematic from the planning service';image.onerror=()=>{image.remove();empty.hidden=false;};image.onload=()=>{empty.hidden=true;};canvas.append(image);}return;}
  empty.hidden=true;
  const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys);
  const correction=Math.cos(((y0+y1)/2)*Math.PI/180),scale=Math.min(540/Math.max((x1-x0)*correction,.001),320/Math.max(y1-y0,.001));
  const project=([lon,lat])=>[300+(lon-(x0+x1)/2)*correction*scale,190-(lat-(y0+y1)/2)*scale];
  mapSVG=svg('svg',{viewBox:view.join(' '),'aria-label':'VT GIS campus geometry with BT observations',role:'img'});
  for(const feature of layers){const props=feature.properties||{},isBuilding=buildingFeatures.includes(feature);const color=/^#[0-9a-f]{6}$/i.test(props.route_color||props.color)?(props.route_color||props.color):props.kind==='closure'?'#a33030':props.source==='GTFS'?'#ef791e':'#547c9c';let element;
   if(feature.geometry.type==='Point'&&coordinate(feature.geometry.coordinates)){const [cx,cy]=project(feature.geometry.coordinates);element=svg('circle',{cx,cy,r:props.kind==='entrance'?3:5,fill:props.kind==='entrance'?'#31784d':color});}
   else{const d=paths(feature.geometry).filter(line=>Array.isArray(line)&&line.every(coordinate)).map(line=>line.map((p,i)=>`${i?'L':'M'}${project(p).join(',')}`).join(' ')+(feature.geometry.type.includes('Polygon')?' Z':'')).join(' ');if(!d)continue;element=svg('path',{d,fill:isBuilding?'#e6e1d5':feature.geometry.type.includes('Polygon')?'#a3303025':'none',stroke:isBuilding?'#8d8577':color,'stroke-width':isBuilding?1:3,'vector-effect':'non-scaling-stroke',...(props.abandoned?{'stroke-dasharray':'5 5',opacity:'.4'}:{})});}
   const title=svg('title');title.textContent=props.name||props.source||'Provided geometry';element.append(title);
   if(isBuilding){element.setAttribute('tabindex','0');element.setAttribute('role','button');element.setAttribute('aria-label',`${props.name||'Building'}: select origin or destination`);element.onclick=()=>selectBuilding(feature);element.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectBuilding(feature);}};}
   mapSVG.append(element);
  }
  for(const vehicle of vehicles){const [cx,cy]=project([vehicle.lon,vehicle.lat]);const marker=svg('circle',{cx,cy,r:6,fill:/^#[0-9a-f]{6}$/i.test(vehicle.route_color)?vehicle.route_color:'#720039',stroke:'#fff','stroke-width':2,tabindex:0,role:'button','aria-label':`Bus ${vehicle.bus_id}, route ${vehicle.route_id}`});const show=()=>{panel.hidden=false;panel.replaceChildren();text(panel,'strong',`Bus ${vehicle.bus_id} · ${vehicle.route_id}`);text(panel,'p',busStatus(vehicle,mapData.is_replay),'helper');text(panel,'p',`Observed at ${vehicle.observed_at||'unknown'} · load ${typeof vehicle.load_pct==='number'?vehicle.load_pct+'%':'unknown'}`,'helper');};marker.onclick=show;marker.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();show();}};mapSVG.append(marker);}
  if(device){const [cx,cy]=project([device.lon,device.lat]);const accuracy=svg('circle',{cx,cy,r:Math.max(4,device.accuracy/111320*scale),fill:'#3e83c322',stroke:'#3e83c3','stroke-width':1});mapSVG.append(accuracy,svg('circle',{cx,cy,r:5,fill:'#3477b2',stroke:'white','stroke-width':2}));}
  canvas.append(mapSVG);
 }
 function populate(){for(const select of [origin,destination]){const previous=select.value;select.replaceChildren(new Option('Choose a building',''));for(const f of buildings){const id=f.properties?.id??f.id;if(id!==undefined)select.add(new Option(f.properties?.name||String(id),String(id)));}select.value=previous;}if(!destination.value&&destinationHint){const match=buildings.find(f=>String(f.properties?.name||'').toLowerCase().includes(destinationHint.toLowerCase().replace(/,.*$/,'')));if(match)destination.value=String(match.properties?.id??match.id);}}
 async function load(){const version=++loadVersion;status.textContent='Loading VT GIS buildings and BT observations…';const results=await Promise.allSettled([request('/api/map/buildings?q='+encodeURIComponent(find('.gis-search').value.trim())),request('/api/map/state')]);if(!alive||version!==loadVersion)return;const failures=[];if(results[0].status==='fulfilled'){const incoming=buildingFeatures(results[0].value);const selected=buildings.filter(f=>[origin.value,destination.value].includes(String(f.properties?.id??f.id)));buildings=[...selected,...incoming.filter(f=>!selected.some(old=>String(old.properties?.id??old.id)===String(f.properties?.id??f.id)))];populate();if(results[0].value?.status==='unavailable')failures.push(results[0].value.reason||'Buildings couldn’t load');}else failures.push('Buildings couldn’t load');if(results[1].status==='fulfilled')mapData=results[1].value;else failures.push('Transit couldn’t refresh');renderMap();status.textContent=failures.length?'Search for a building or try refreshing the map.':`${mapData.is_replay?'Pinned replay':'Observed snapshots'} · VT GIS paths / BT GTFS routes · ${mapData.observed_at||'Observation time unavailable'}`;}
 find('.gis-route').onclick=async()=>{const button=find('.gis-route');if(button.disabled)return;let body;try{body=routePayload(origin.value,destination.value,mode);}catch(error){status.textContent=error.message;return;}button.disabled=true;status.textContent='Checking the selected campus route…';try{const data=await request('/api/route',{method:'POST',body:JSON.stringify(body)});if(!alive)return;routeData=normalizedRoute(data);renderMap();const summary=find('.gis-route-summary');summary.replaceChildren();
 const failed=['no_route','unavailable'].includes(data.status)||data.feasible===false;
 text(summary,'strong',data.status==='no_route'?'No route found for this mode':data.status==='unavailable'?'Route service unavailable':data.feasible===false?'No route fits these constraints.':'Campus walking route');
 text(summary,'p',data.message||data.reason||(failed?'Try another route.':'Review the route and directions below.'),'helper');
 if(!failed){
 if(Number.isFinite(data.distance_m))text(summary,'p',`${Math.round(data.distance_m)} m · walking distance`,'helper');
 if(Number.isFinite(data.estimated_minutes))text(summary,'p',`${data.estimated_minutes} min estimate · ${data.estimated_minutes_label||'Estimated walking time; not a GIS travel time.'}`,'helper');
 if(data.closures_considered!==true)text(summary,'p','Closures are not applied to this route. Check current conditions.','helper');
 const steps=Array.isArray(data.directions)?data.directions:[];
 if(steps.length){const list=document.createElement('ol');for(const step of steps)text(list,'li',step.text||'');summary.append(list);}
 }
 const provenance=data.provenance;
 if(provenance?.attribution)text(summary,'p',provenance.attribution,'helper');
 if(provenance?.disclaimer)text(summary,'p',provenance.disclaimer,'helper');
 for(const note of Array.isArray(data.notes)?data.notes:[])text(summary,'p',note,'helper');
 status.textContent=failed?'No usable route returned.':'VT GIS walking route · no multimodal comparison.';
 }catch(error){if(alive)status.textContent=error.message;}finally{if(alive)button.disabled=false;}};
 for(const button of root.querySelectorAll('[data-mode]'))button.onclick=()=>{mode=button.dataset.mode;root.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));};
 const viewport=find('.gis-viewport');function setView(){mapSVG?.setAttribute('viewBox',view.join(' '));}function zoom(factor){const w=view[2]*factor,h=view[3]*factor;if(w<60||w>2400)return;view=[view[0]+(view[2]-w)/2,view[1]+(view[3]-h)/2,w,h];setView();}
 const controls=root.querySelectorAll('.gis-zoom button');controls[0].onclick=()=>zoom(.8);controls[1].onclick=()=>zoom(1.25);controls[2].onclick=()=>{view=[0,0,600,380];setView();};
 viewport.onkeydown=e=>{if(e.target!==viewport)return;const delta=view[2]/12;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','+','-','='].includes(e.key)){e.preventDefault();if(e.key==='ArrowUp')view[1]-=delta;if(e.key==='ArrowDown')view[1]+=delta;if(e.key==='ArrowLeft')view[0]-=delta;if(e.key==='ArrowRight')view[0]+=delta;if(e.key==='+'||e.key==='=')zoom(.8);if(e.key==='-')zoom(1.25);setView();}};
 viewport.onpointerdown=e=>{if(e.target.closest('button,[role=button]')||!mapSVG)return;drag={x:e.clientX,y:e.clientY,view:[...view]};viewport.setPointerCapture(e.pointerId);};viewport.onpointermove=e=>{if(!drag)return;const ratio=drag.view[2]/viewport.clientWidth;view=[drag.view[0]-(e.clientX-drag.x)*ratio,drag.view[1]-(e.clientY-drag.y)*ratio,drag.view[2],drag.view[3]];setView();};viewport.onpointerup=()=>drag=null;viewport.onpointercancel=()=>drag=null;
 function stopLocation(){if(watch!==null)navigator.geolocation?.clearWatch(watch);watch=null;device=null;find('.gis-locate').textContent='Use my location';renderMap();}
 find('.gis-locate').onclick=()=>{if(watch!==null){stopLocation();return;}const note=find('.gis-location-note');if(!window.isSecureContext||!navigator.geolocation){note.textContent='Location needs HTTPS or localhost. Choose a building instead.';return;}note.textContent='Your browser will ask permission. Location is only shown on this map; it is not stored.';watch=navigator.geolocation.watchPosition(position=>{if(!alive)return;const {latitude:lat,longitude:lon,accuracy}=position.coords;const radians=n=>n*Math.PI/180;const dlat=radians(lat-37.2296),dlon=radians(lon+80.424);const a=Math.sin(dlat/2)**2+Math.cos(radians(lat))*Math.cos(radians(37.2296))*Math.sin(dlon/2)**2;const km=6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));if(km>5){stopLocation();note.textContent='Location is more than 5 km from campus. Choose a building instead.';return;}device={lat,lon,accuracy};note.textContent=`Your location ±${Math.round(accuracy)} m · only on this map`;find('.gis-locate').textContent='Stop using location';renderMap();},()=>{stopLocation();note.textContent='Location unavailable or permission denied. Choose a building instead.';},{enableHighAccuracy:false,maximumAge:60000,timeout:10000});};
 let searchTimer;find('.gis-search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>void load(),400);};find('.gis-retry').onclick=()=>void load();void load();poll=setInterval(async()=>{try{const next=await request('/api/map/state');if(alive){mapData=next;renderMap();status.textContent=`${mapData.is_replay?'Pinned replay':'Observed snapshots'} · ${mapData.observed_at||'Observation time unavailable'}`;}}catch{if(alive)status.textContent='Couldn’t refresh the map. Please try again.';}},60000);
 const close=()=>{alive=false;abort.abort();clearTimeout(searchTimer);clearInterval(poll);if(watch!==null)navigator.geolocation?.clearWatch(watch);window.removeEventListener('pagehide',close);};window.addEventListener('pagehide',close);
 return {destroy:close,setDestinationHint(hint){destinationHint=hint;find('.gis-search').value=hint;void load();destination.focus();}};
}
